version: "3"

services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    volumes:
      - ./rails:/app
    ports:
      - 3000:3000
    environment:
      - HUB_URL=http://chrome:4444/wd/hub
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900