version: "3"

services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - RAILS_SYSTEM_TESTING_SCREENSHOT=inline
      - ACTIVE_ADMIN_USERNAME=${ACTIVE_ADMIN_USERNAME}
      - ACTIVE_ADMIN_PASSWORD=${ACTIVE_ADMIN_PASSWORD}
    depends_on:
      - db
      - chrome

  chrome:
    # image: selenium/standalone-chrome-debug:latest
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      # - 5900:5900