Project Larticle {
  database_type: 'PostgreSQL'
}

Table articles {
  id integer [pk, increment]
  uid string [not null]
  url text [not null, note: "max-length: 2000"]
  title string [not null]
  image_url text
  finish_reading_at datetime
  memo text [note: "max-length: 1000"]
  created_at timestamp [not null]
  updated_at timestamp [not null]
}

Table users {
  uid string [pk]
  provider string
  Note: "auth0. https://github.com/auth0/omniauth-auth0#auth-hash"
}

Ref: users.uid - articles.uid