Project Larticle {
  database_type: 'PostgreSQL'
}

Table articles {
  id string [pk, increment]
  url text [not null, note: "max-length: 2000"]
  title string
  description text
  ogp_url text
  // finish_reading_at timestamp [note: '記事を読み終えた日時']
  created_at timestamp [not null]
  updated_at timestamp [not null]
}